apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-example-front-proxy
spec:
  environments:
    - name: prod
      build:
        from: master
  components:
    - name: auth-proxy
      image: quay.io/pusher/oauth2_proxy:v4.0.0
      publicPort: http
      secrets:
        - OAUTH2_PROXY_CLIENT_SECRET # client secret for the UI. Application exist under Azure Active Directory -> App registration
        - OAUTH2_PROXY_COOKIE_SECRET # a secret key used to encrypt the auth tokens sent to browser in cookie 
      ports:
        - name: http
          port: 8000
      environmentConfig:
        - environment: prod
          variables:
            OAUTH2_PROXY_PROVIDER: "oidc" # https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc
            OAUTH2_PROXY_OIDC_ISSUER_URL: "https://login.microsoftonline.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/v2.0" # the UID points to Equinors AzureAd tenant
            OAUTH2_PROXY_CLIENT_ID: "814607e6-3d71-44a7-8476-50e8b281abbc" # client id for the UI. Application exist under Azure Active Directory -> App registration
            OAUTH2_PROXY_SCOPE: "openid profile 30bb41bb-be29-4b10-aef7-f759141b9923/user_impersonation email" # UID is resource client id for API. Application exist under Azure Active Directory -> App registration
            OAUTH2_PROXY_REDIRECT_URL: "https://radix-example-front-proxy.app.playground.radix.equinor.com/oauth2/callback"
            OAUTH2_PROXY_HTTP_ADDRESS: "http://:8000"
            OAUTH2_PROXY_UPSTREAMS: "http://frontend:8001" # where authenticated requests are routed to
            OAUTH2_PROXY_COOKIE_REFRESH: "60m" # how often should the token be refreshed. Default for azure ad is currently 60m
            OAUTH2_PROXY_EMAIL_DOMAINS: "*"
            OAUTH2_PROXY_PASS_ACCESS_TOKEN: "true" # should the access token be passed upstream (to the server hosting frontend component).
            OAUTH2_PROXY_PASS_BASIC_AUTH: "false"
            OAUTH2_PROXY_PASS_USER_HEADERS: "false"
            OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
    - name: frontend
      src: frontend
      ports:
        - name: http
          port: 8001
    - name: api
      src: api
      publicPort: http
      ports:
        - name: http
          port: 8002
      environmentConfig:
        - environment: prod
          variables:
            API_RESOURCE_ID: "30bb41bb-be29-4b10-aef7-f759141b9923" # client id for the API. Application exist under Azure Active Directory -> App registration
            AZURE_AD_PUBLIC_KEY: "|
              -----BEGIN PUBLIC KEY-----
              MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp2DzxOZiWEHhtVavuwIm
              ryTRxW4kJ0mbA1lbXon550DUnKDZCNZaztno8HpOl6NSbVbW+QLDz5VOqCn+PDvS
              IRcw+2hrJPRnCNob4yGEuC7v9dPVpPDFRiUrOcwCbJak6xsK9PEsX8FQ/onFHO6Y
              JkjsFG8S2nMhgRK+JdURUcuj9paywSBtW9ddeqjQPgCPbZJtk39ReouoBYNm9xiw
              hTN0InY9Rt9PKUh4cRetg3OeKQ2E8TOVh1nHeTT2HIIYnAgB7ESUA07wYBuvet4U
              GemC2SdfpTSWk2YqzjZONW8p01hJg9x8lcSeyaQVOxTP/SjQoP99la1V8lArF35q
              xQIDAQAB
              -----END PUBLIC KEY-----" # public key: corresponding private key is used to sign tokens by Azure AD 
  dnsAppAlias:
    environment: prod
    component: auth-proxy
